### ISSUE TITLE
Revision History: Retro board

### ISSUE THREAD

**Issue by pmswatuser** [RallyCommunity/IterationRetro#2]
@krmorse  Does this custom app maintain revision history for content posted?

If content is accidentally deleted from this app, is there anyway to track the change or retrieve it? Currently, the content could be deleted by anyone anonymously without any tracking.

Thanks in advance.

**Comment by pmswatuser** [comment]
@krmorse

**Comment by krmorse** [comment]
The content is all stored in custom fields on the underlying iteration object itself.  So even if the app is deleted the data will still be there.  Additionally, since the data is stored in custom fields it should be available in the revision history for the underlying iteration object.  Hope that helps!

**Comment by pmswatuser** [comment]
Thanks for your response. I was able to fetch the custom field data. If someone accidentally deletes content from these fields (for a given iteration), is there anyway we can trace the user? Not sure if user field is tied to iteration object.

**Comment by pmswatuser** [comment]
@krmorse  I was able to track the revisions. Thanks for your input.

**Comment by pmswatuser** [comment]
@krmorse some of the revisions under revision history JSON array show this line:

"Description": "RETRO DELTAS changed from [value too long to display] to [value too long to display]"

When the content of the field is too long, it doesn't bring back the full content. Any thoughts?

**Comment by krmorse** [comment]
Hmm, yeah unfortunately that's a limitation of the revision history in rally.  Long fields get truncated like that.  womp womp.  I don't really have a great workaround for you...

**Comment by pmswatuser** [comment]
Thank you
